parameters:
    bdxmlrpc.request_listener.class: BD\Bundle\XmlRpcBundle\EventListener\RequestEventListener
    bdxmlrpc.request_parser.class: BD\Bundle\XmlRpcBundle\XmlRpc\RequestParser

services:
    bdxmlrpc.request_listener:
        class: %bdxmlrpc.request_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
            - @http_kernel
            - @router
            - @bdxmlrpc.request_generator

    bdxmlrpc.request_parser:
        class: %bdxmlrpc.request_parser.class%

    bdxmlrpc.request_generator:
        class: %bdxmlrpc.request_generator%
        arguments:
            - @bdxmlrpc.request_parser