# Sets XML-RPC services to use the XmlRpc/Handler/Ext versions (php5-xmlrpc)
services:
    bdxmlrpc.request_parser:
        alias: bdxmlrpc.request_parser.ext

    bdxmlrpc.response_generator:
        alias: bdxmlrpc.response_generator.ext
